{"cells":[{"cell_type":"markdown","metadata":{},"source":["---\n","# 5. Exceptions\n","---\n","\n","When an error occurs during execution, an exception is raised. \n"]},{"cell_type":"code","execution_count":1,"metadata":{},"outputs":[{"ename":"IndexError","evalue":"list index out of range","output_type":"error","traceback":["\u001b[1;31m---------------------------------------------------------------------------\u001b[0m","\u001b[1;31mIndexError\u001b[0m                                Traceback (most recent call last)","\u001b[1;32mC:\\Users\\GARETH~1\\AppData\\Local\\Temp/ipykernel_22548/1524988906.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[1;31m# Example of an IndexError\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      2\u001b[0m \u001b[0mmy_list\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;33m[\u001b[0m\u001b[1;36m1\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;36m2\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;36m3\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 3\u001b[1;33m \u001b[0mmy_list\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;36m3\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[1;31mIndexError\u001b[0m: list index out of range"]}],"source":["# Example of an IndexError\n","my_list = [1, 2, 3]\n","my_list[3]"]},{"cell_type":"code","execution_count":2,"metadata":{},"outputs":[{"ename":"ZeroDivisionError","evalue":"division by zero","output_type":"error","traceback":["\u001b[1;31m---------------------------------------------------------------------------\u001b[0m","\u001b[1;31mZeroDivisionError\u001b[0m                         Traceback (most recent call last)","\u001b[1;32mC:\\Users\\GARETH~1\\AppData\\Local\\Temp/ipykernel_22548/812818711.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[1;31m# Example of a ZeroDivisionError\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 2\u001b[1;33m \u001b[1;36m50\u001b[0m \u001b[1;33m/\u001b[0m \u001b[1;36m0\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[1;31mZeroDivisionError\u001b[0m: division by zero"]}],"source":["# Example of a ZeroDivisionError\n","50 / 0\n"]},{"cell_type":"markdown","metadata":{},"source":["## 5.1 Raising Exceptions\n","\n","Exceptions indicate errors and break out of the normal control flow of a program.\n","Exceptions can be raised using the `raise` statement.\n","\n"]},{"cell_type":"code","execution_count":7,"metadata":{},"outputs":[],"source":["# Define a function to divide one number by another\n","\n","def my_divide(numerator, denominator):\n","    if denominator == 0:\n","        print(\"Denominator is 0.\")\n","        # raise Exception()\n","        msg = \"Cannot divide by zero.\"\n","        raise ZeroDivisionError(msg)\n","    else:\n","        return numerator / denominator\n"]},{"cell_type":"code","execution_count":8,"metadata":{},"outputs":[{"name":"stdout","output_type":"stream","text":["Denominator is 0.\n"]},{"ename":"ZeroDivisionError","evalue":"Cannot divide by zero.","output_type":"error","traceback":["\u001b[1;31m---------------------------------------------------------------------------\u001b[0m","\u001b[1;31mZeroDivisionError\u001b[0m                         Traceback (most recent call last)","\u001b[1;32mC:\\Users\\GARETH~1\\AppData\\Local\\Temp/ipykernel_22548/3325886613.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[1;32m----> 1\u001b[1;33m \u001b[0mmy_divide\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;36m50\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;36m0\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[1;32mC:\\Users\\GARETH~1\\AppData\\Local\\Temp/ipykernel_22548/658192037.py\u001b[0m in \u001b[0;36mmy_divide\u001b[1;34m(numerator, denominator)\u001b[0m\n\u001b[0;32m      6\u001b[0m         \u001b[1;31m# raise Exception()\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      7\u001b[0m         \u001b[0mmsg\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;34m\"Cannot divide by zero.\"\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 8\u001b[1;33m         \u001b[1;32mraise\u001b[0m \u001b[0mZeroDivisionError\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mmsg\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m      9\u001b[0m     \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     10\u001b[0m         \u001b[1;32mreturn\u001b[0m \u001b[0mnumerator\u001b[0m \u001b[1;33m/\u001b[0m \u001b[0mdenominator\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n","\u001b[1;31mZeroDivisionError\u001b[0m: Cannot divide by zero."]}],"source":["my_divide(50, 0)"]},{"cell_type":"markdown","metadata":{},"source":["## 5.2  Handling Exceptions with a Single `except` block\n","\n","\n","- Exceptions are 'caught' in the `try` block and then 'handled' in the `except` block.  \n","- Excution stops in the `try` block as soon as the exception is encountered, and jumps straight to the `except` block.  \n"]},{"cell_type":"code","execution_count":11,"metadata":{},"outputs":[{"name":"stdout","output_type":"stream","text":["Denominator is 0.\n","Something went wrong...\n","Continue with the rest of the program...\n"]}],"source":["# Our function will raise an Exception...\n","# Which print statements will be executed?\n","n = 10\n","d = 0\n","try:\n","    print(my_divide(n, d)) # risky thing\n","except: # Caught the ZeroDivisionError\n","    print(\"Something went wrong...\") # If risky thing raise an exception, do this instead\n","\n","print(\"Continue with the rest of the program...\")"]},{"cell_type":"markdown","metadata":{},"source":["### Concept check: raising an Exception from within a function\n","\n","In an earlier unit (PY01.01.Intro.08.Functions), we wrote the function `get_age_from_string` that has a single argument `user_input`, and returns an integer if possible, or else `'not known` if the `user_input` is invalid (for example, if the user enters letters rather than numbers, or a negative number.).\n","\n","That function has been copied into the `exceptions_exercises` module, and running `pytest` should show it passing one unit test. \n","\n","In this exercise, we'll add a slightly different function to that module, `get_age_from_string_v2`, that raises an `Exception` if the input is invalid. (Rather than return the string `'not known'`, as before). The `Exception` that we raise must include the word `'Invalid'` in its message (The unit test for this exercise searches for this).  \n","\n","Write code to call your function with some example names, either here in this notebook or else in the `__main__` block of the `exceptions_exercises` module.  Print out the input arguments and return values, to show that it is working.\n","\n","When it's ready to test, remove the first `@pytest.mark.skip line` from `test_for_exceptions.py` and rerun pytest. \n","\n","\n"]},{"cell_type":"markdown","metadata":{},"source":["## 5.3 Multiple `except` Blocks\n","\n","- We can have multiple `except` blocks for different kinds of exceptions.\n","- Each `except` block is considered in turn (starting with the first one). - If the type of the raised `Exception` matches the type in the `except` block, then this block is selected for execution (and no other `except` blocks will be executed). \n","- The matching is performed using the hierachy of Python exception types. A list of the built-in exception types can be found [here](https://docs.python.org/3/library/exceptions.html?highlight=exception#Exception). "]},{"cell_type":"code","execution_count":15,"metadata":{},"outputs":[{"name":"stdout","output_type":"stream","text":["Zero division error!\n"]}],"source":["# Zero division error\n","try:\n","    50 / 0 # Can throw multiple types of error\n","except IndexError:\n","    print(\"Index Error!\")\n","except ZeroDivisionError:\n","    print(\"Zero division error!\")\n","except: # Catch all leftover errors\n","    print(\"Something went wrong...\")\n"]},{"cell_type":"code","execution_count":16,"metadata":{},"outputs":[{"name":"stdout","output_type":"stream","text":["Index Error!\n"]}],"source":["# Index error\n","try:\n","    my_list = [1, 2, 3]\n","    my_list[10] # Can throw multiple types of error\n","except IndexError:\n","    print(\"Index Error!\")\n","except ZeroDivisionError:\n","    print(\"Zero division error!\")\n","except: # Catch all leftover errors\n","    print(\"Something went wrong...\")\n"]},{"cell_type":"code","execution_count":17,"metadata":{},"outputs":[{"name":"stdout","output_type":"stream","text":["Something went wrong...\n"]}],"source":["# File not found error\n","try:\n","    f = open(\"thisdoesnotexist.txt\", \"r\")\n","except IndexError:\n","    print(\"Index Error!\")\n","except ZeroDivisionError:\n","    print(\"Zero division error!\")\n","except: # Catch all leftover errors\n","    print(\"Something went wrong...\")"]},{"cell_type":"code","execution_count":19,"metadata":{},"outputs":[{"ename":"SyntaxError","evalue":"default 'except:' must be last (Temp/ipykernel_22548/581501938.py, line 4)","output_type":"error","traceback":["\u001b[1;36m  File \u001b[1;32m\"C:\\Users\\GARETH~1\\AppData\\Local\\Temp/ipykernel_22548/581501938.py\"\u001b[1;36m, line \u001b[1;32m4\u001b[0m\n\u001b[1;33m    my_list[10]\u001b[0m\n\u001b[1;37m    ^\u001b[0m\n\u001b[1;31mSyntaxError\u001b[0m\u001b[1;31m:\u001b[0m default 'except:' must be last\n"]}],"source":["# Zero division error\n","try:\n","    my_list = [1, 2, 3]\n","    my_list[10]\n","except Exception:\n","    print(\"An exception occured!\")\n","except IndexError:\n","    print(\"Index Error!\")\n","except ZeroDivisionError:\n","    print(\"Zero division error!\")\n","except: # Catch all leftover errors\n","    print(\"Something went wrong...\")"]},{"cell_type":"markdown","metadata":{},"source":["### Concept check: raising different types of Exceptions from within  a function\n","\n","\n","In this exercise, we'll write a new function, `get_age_from_string_v3`, that raises an `TypeError` if the input cannot to converted into an integer, and a `ValueError` if the value is less than zero, or more than 150. \n","\n","Write code to call your function with some example inputs. Print out one message if your function raises a `ValueError`, and another message if your function raises a `TypeError`. (This code can go either here in this notebook, or else in the `__main__` block of the `exceptions_exercises` module.)\n","\n","When it's ready to test, remove the second `@pytest.mark.skip line` from `test_for_exceptions.py`, and rerun pytest. \n","\n"]},{"cell_type":"code","execution_count":20,"metadata":{},"outputs":[{"data":{"text/plain":["['__cause__',\n"," '__class__',\n"," '__context__',\n"," '__delattr__',\n"," '__dict__',\n"," '__dir__',\n"," '__doc__',\n"," '__eq__',\n"," '__format__',\n"," '__ge__',\n"," '__getattribute__',\n"," '__gt__',\n"," '__hash__',\n"," '__init__',\n"," '__init_subclass__',\n"," '__le__',\n"," '__lt__',\n"," '__ne__',\n"," '__new__',\n"," '__reduce__',\n"," '__reduce_ex__',\n"," '__repr__',\n"," '__setattr__',\n"," '__setstate__',\n"," '__sizeof__',\n"," '__str__',\n"," '__subclasshook__',\n"," '__suppress_context__',\n"," '__traceback__',\n"," 'args',\n"," 'with_traceback']"]},"execution_count":20,"metadata":{},"output_type":"execute_result"}],"source":["dir(Exception)"]}],"metadata":{"interpreter":{"hash":"54b57a9d7255aa9bd89013014712be1af3e9c0518087b34529522b12b0bc87de"},"kernelspec":{"display_name":"Python 3.9.7 ('base')","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.9.7"}},"nbformat":4,"nbformat_minor":2}
